/**
 * Maintainer build. Keeps every generated file in step with src/:
 *
 *   docs/platform-specs.md             generated from src/specs.js
 *   skills/brandshot/scripts/*         the CLI + src, flattened so the skill is self-contained
 *   skills/brandshot/assets/…          the starter config
 *   skills/brandshot/references/platform-specs.md
 *   dist/brandshot-skill.zip           upload-ready for claude.ai and ChatGPT
 *
 *   node scripts/build.mjs           build
 *   node scripts/build.mjs --check   fail if anything is out of date (CI / pre-commit)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ASSETS, TEXT_LIMITS, pixelSize } from '../src/specs.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const stale = [];

function emit(rel, content) {
  const file = join(root, rel);
  const before = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (before === content) return;
  if (check) { stale.push(rel); return; }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${rel}`);
}

/* ------------------------------------------------------ platform specs --- */

const SOURCES = `## Sources

Official pages, checked 2026-09-19:

- YouTube banner and profile picture: https://support.google.com/youtube/answer/10456525
- YouTube thumbnails: https://support.google.com/youtube/answer/72431
- Instagram photo resolution: https://help.instagram.com/1631821640426723
- Meta Stories / Reels safe zones: https://www.facebook.com/business/ads-guide/update/image/instagram-story
- LinkedIn profile photo: https://www.linkedin.com/help/linkedin/answer/a549049
- LinkedIn background photo: https://www.linkedin.com/help/linkedin/answer/a568217
- LinkedIn Page images: https://www.linkedin.com/help/linkedin/answer/a563309
- X profile and header: https://help.x.com/en/managing-your-account/common-issues-when-uploading-profile-photo
- Facebook Page photos: https://www.facebook.com/help/125379114252045
- Open Graph images: https://developers.facebook.com/docs/sharing/webmasters/images/
- TikTok profile photo: https://www.tiktok.com/support/faq_detail?id=7581821549855038008
- Pinterest product specs: https://help.pinterest.com/en/business/article/pinterest-product-specs
- GitHub social preview: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview
- Bluesky limits come from the app's source: https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/actor/profile.json

Avatar-overlap regions and some profile-picture sizes are not documented by the platforms. They were measured from current layouts and secondary guides (Hootsuite, Kapwing, Snappa), so treat them as close approximations.

## Recent changes that most guides still get wrong

- **LinkedIn company cover:** 1512×256 (was 1128×191).
- **Instagram:** the profile grid shows 3:4 tiles, and feed photos are kept between 1.91:1 and 3:4, so 1080×1440 fills a tile exactly.
- **X header:** up to 60 px can be cut from the top and bottom.
- **YouTube thumbnails:** up to 3840×2160 and 50 MB.
- **Facebook cover:** shown at several ratios (16:9, 2.4:1, 2.63:1). 1640×924 with the text inside the centred 1640×624 band covers all of them.
`;

function specsDoc() {
  const byPlatform = {};
  for (const a of ASSETS) (byPlatform[a.platform] ??= []).push(a);
  const box = (b) => (b ? `x ${b.x}–${b.x + b.w}, y ${b.y}–${b.y + b.h}` : '');
  const sections = Object.entries(byPlatform).map(([p, list]) => {
    const rows = list.map((a) => {
      const px = pixelSize(a);
      return `| \`${a.id}\` | ${a.label} | ${px.w}×${px.h} | ${a.content ? box(a.content) : 'centre 70% (circle crop)'} | ${a.notes ?? ''} |`;
    }).join('\n');
    return `### ${p}\n\n| File | What | Size | Text area | Notes |\n| --- | --- | --- | --- | --- |\n${rows}`;
  }).join('\n\n');
  const limits = Object.entries(TEXT_LIMITS).map(([p, l]) =>
    `| ${p} | ${Object.entries(l).map(([k, v]) => `${k}: ${v.toLocaleString('en-US')}`).join(' · ')} |`).join('\n');
  return `# Platform specs

<!-- Generated by scripts/build.mjs from src/specs.js. Edit that file, not this one. -->

What brandshot renders, at which size, and where the text goes. "Text area" is the \`content\` box: the part every device shows that no avatar or app UI covers.

${sections}

## Profile text limits

| Platform | Limits (characters) |
| --- | --- |
${limits}

${SOURCES}`;
}

const specs = specsDoc();
emit('docs/platform-specs.md', specs);
emit('skills/brandshot/references/platform-specs.md', specs);

/* ------------------------------------------------------ skill scripts ---- */

// The skill must work on its own (claude.ai / ChatGPT uploads have no repo),
// so the CLI and src/ are copied in with their imports flattened.
const flatten = (s) => s.replaceAll("'../src/", "'./").replaceAll("'../brand.example.json'", "'../assets/brand.example.json'");
emit('skills/brandshot/scripts/brandshot.mjs', flatten(readFileSync(join(root, 'bin/brandshot.mjs'), 'utf8')));
for (const f of ['templates.js', 'tiles.js', 'specs.js', 'util.js']) {
  emit(`skills/brandshot/scripts/${f}`, readFileSync(join(root, 'src', f), 'utf8'));
}
emit('skills/brandshot/assets/brand.example.json', readFileSync(join(root, 'brand.example.json'), 'utf8'));

/* ------------------------------------------------------ zip -------------- */

if (check) {
  if (stale.length) {
    console.error(`Out of date, run "npm run build":\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('Generated files are up to date.');
} else {
  const zip = join(root, 'dist', 'brandshot-skill.zip');
  mkdirSync(dirname(zip), { recursive: true });
  rmSync(zip, { force: true });
  // -X drops extra file attributes and the fixed file order keeps the archive
  // reproducible between builds.
  execFileSync('zip', ['-qrX', zip, 'brandshot', '-x', '*.DS_Store'], { cwd: join(root, 'skills') });
  console.log('wrote dist/brandshot-skill.zip');
}
